# -*- coding: utf-8 -*-
"""Challenge 03.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebHr8VC1RN791cW_3GUrMHxsDJ5l0T2s
"""

def linearSearchProduct(productList,targetProduct):
   indices = []

   for index,product in enumerate(productList):
     if product == targetProduct:
       indices.append(index)

   return indices


# Example Usage:
products = ["shoes","boot","loafer","shoes","sandal","shoes"]
target = "shoes"
target2 = 'apple'
result = linearSearchProduct(products,target)
print(result)