# -*- coding: utf-8 -*-
"""challenge02.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJt7tUIct4qMdkIiODJjV5yrW04VVcBC
"""

class Player:
  def play(self):
    print("The player is playing Cricket.")
class Batsman(Player):
  def play(self):
    print("The batsman is batting.")
class Bowler(Player):
  def play(self):
    print("The bowler is bowlig.")
batsman=Batsman()
bowler=Bowler()
batsman.play()
bowler.play()