# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixsmSXNmC16Ia4y2pDNY1-ckN22R-1F8
"""

def fact_rec(n):
  if n==0 or n==1:
    return 1
  else:
    return n*fact_rec(n-1)

number=2
res=fact_rec(number)
print("The factorial of {} is {}.".format(number,res))