# -*- coding: utf-8 -*-
"""challenge 1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1orVRdt4zkYR8Rt-Jv3VHHZFOqJg0pG_1
"""

def isleapyear(year):
  if (year%4==0 and year%100!=0) or year%400==0:
    return True
  else:
    return False
year=2013
if isleapyear(year):
 print("{} is a leap year.".format(year))
else:
 print("{} is not a leap year.".format(year))